<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	  <OutputPath>$(SolutionDir)\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
	  <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\courier.png" />
    <None Remove="Images\courier_removed.png" />
    <None Remove="Images\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\courier.png" />
    <Resource Include="Images\logo.png" />
  </ItemGroup>

</Project>
