using DalApi;

namespace Helpers;

/// <summary>
/// a static class for managing delivery-related operations within the business logic layer.
/// </summary>
internal static class DeliveryManager
{
    //an object for accessing the DAL methods
    private static IDal s_dal = Factory.Get;

    //an observer manager for delivery-related events
    internal static ObserverManager Observers = new();


    /// <summary>
    /// gets a specific delivery by its ID.
    /// </summary>
    /// <param name="deliveryId"></param>
    /// <returns></returns>
    internal static DO.Delivery ReadDelivery(int deliveryId)
    {
        // Validate existence by calling the helper method.
        return GetExistingDelivery(deliveryId);
    }

    /// <summary>
    /// gets all delivery records, optionally filtered by a predicate.
    /// </summary>
    /// <param name="predicate"></param>
    /// <returns></returns>
    internal static IEnumerable<DO.Delivery> ReadAllDeliveries(Func<DO.Delivery, bool>? predicate = null)
    {
        return s_dal.Delivery.ReadAll(predicate);
    }

    /// <summary>
    /// creates a new delivery record for the specified order and courier,
    /// When writing this function, we used AI to ensure that the logic and sorting order were correct.
    /// </summary>
    /// <param name="orderId"></param>
    /// <param name="courierId"></param>
    /// <param name="orderLat"></param>
    /// <param name="orderLon"></param>
    /// <param name="shippingType"></param>
    /// <exception cref="BO.BlInvalidOperationException"></exception>
    internal static void CreateNewDeliveryForOrder(int orderId, int courierId, double orderLat, double orderLon, BO.DeliveryType shippingType)
    {
        DO.Courier? courierToCheck = s_dal.Courier.Read(courierId);

        // validate courier existence and status
        if (courierToCheck == null)
            throw new BO.BlDoesNotExistException($"Courier {courierId} does not exist.");

        // only active couriers can be assigned
        if (!courierToCheck.IsActive)
            throw new BO.BlInvalidOperationException($"Cannot assign order to inactive courier {courierId}.");

        // cordinates of the company (source)
        (double companyLat, double companyLon) = OrderManager.GetCompanyCoordinates();

        if (orderLat == 0 || orderLon == 0)
        {
            // default address value in Israel for routing to work
            orderLat = 32.07;
            orderLon = 34.77;
        }

        // calculate actual distance and estimated time
        (double actualDistance, TimeSpan estimatedTime)? routingResult;
        try
        {
            routingResult = Tools.GetActualDistanceAndEstimatedTimeSync(
                companyLat, companyLon, orderLat, orderLon, shippingType
            );
        }
        catch (Exception ex)
        {
            throw new BO.BlInvalidOperationException($"Routing failed. Please check internet and coordinates. Internal error: {ex.Message}");
        }

        if (!routingResult.HasValue)
            throw new BO.BlInvalidOperationException("Routing service failed to calculate distance and time for the selected order/courier.");

        // create new DO.Delivery record
        DateTime deliveryStartTime = AdminManager.Now;

        DO.Delivery newDelivery = new DO.Delivery(
            Id: default, // generated by DAL
            OrderId: orderId,
            CourierId: courierId,
            TypeOfOrder: OrderManager.GetExistingOrder(orderId).TypeOfOrder,
            DeliveryStartTime: deliveryStartTime,

            // saved values from routing calculation
            ActualDistance: routingResult.Value.actualDistance,

            OrderClosedStatus: null, // open
            DeliveryEndTime: null // open
        );

        // add to DAL
        s_dal.Delivery.Create(newDelivery);

        // Notify observers about the new delivery
        Observers.NotifyListUpdated();
    }

    /// <summary>
    /// completes an existing delivery by updating its end time and status.
    /// </summary>
    /// <param name="courierId"></param>
    /// <param name="deliveryId"></param>
    /// <exception cref="BO.BlInvalidOperationException"></exception>
    internal static void CompleteDeliveryUpdate(int courierId, int deliveryId, BO.OrderEndStatus status)
    {
        // validate delivery existence
        DO.Delivery doDelivery = GetExistingDelivery(deliveryId);

        // validate courier assignment
        if (doDelivery.CourierId != courierId)
            throw new BO.BlInvalidOperationException($"Courier {courierId} is not assigned to delivery {deliveryId}.");

        // validate delivery is not already completed
        if (doDelivery.DeliveryEndTime.HasValue)
            throw new BO.BlInvalidOperationException($"Delivery {deliveryId} is already completed.");

        // update delivery record to mark as completed
        DO.Delivery updatedDelivery = doDelivery with
        {
            DeliveryEndTime = AdminManager.Now,
            OrderClosedStatus = (DO.OrderEndStatus)status
        };

        // save update to DAL
        s_dal.Delivery.Update(updatedDelivery);

        // Notify observers about the update
        Observers.NotifyItemUpdated(deliveryId);
        Observers.NotifyListUpdated();
    }

    /// <summary>
    /// / gets an existing delivery or throws an exception if not found.
    /// </summary>
    /// <param name="deliveryId"></param>
    /// <returns></returns>
    /// <exception cref="BO.BlDoesNotExistException"></exception>
    private static DO.Delivery GetExistingDelivery(int deliveryId)
    {
        var delivery = s_dal.Delivery.Read(deliveryId);

        // validate existence
        if (delivery == null)
            throw new BO.BlDoesNotExistException($"Delivery with ID {deliveryId} does not exist.");
    
        return delivery;
    }

    /// <summary>
    /// gets all closed deliveries for a specific courier, optionally filtered by order type.
    /// </summary>
    /// <param name="courierId"></param>
    /// <param name="filterByType"></param>
    /// <returns></returns>
    internal static IEnumerable<BO.ClosedDeliveryInList> GetClosedDeliveriesForCourier(int courierId, BO.OrderType? filterByType = null)
    {
        // Read courier details once outside the loop
        var courier = s_dal.Courier.Read(courierId);
        if (courier == null)
            throw new BO.BlDoesNotExistException($"Courier {courierId} not found");

        var courierDeliveryType = (BO.DeliveryType)courier.TypeOfDelivery;

        // Retrieve all closed deliveries
        var deliveries = s_dal.Delivery.ReadAll(d =>
            d.CourierId == courierId &&
            d.DeliveryEndTime.HasValue);

        // Map to BO using the pre-fetched courier data
        var closedDeliveries = deliveries.Select(doDelivery =>
        {
            // Fetch order details
            DO.Order doOrder = OrderManager.GetExistingOrder(doDelivery.OrderId);

            // calculate total handling duration
            TimeSpan totalHandlingDuration = doDelivery.DeliveryEndTime!.Value - doDelivery.DeliveryStartTime;

            // map to BO.ClosedDeliveryInList
            return new BO.ClosedDeliveryInList
            {
                Id = doDelivery.Id,
                OrderId = doDelivery.OrderId,
                TypeOfOrder = (BO.OrderType)doOrder.TypeOfOrder,
                Address = doOrder.Address,
                TypeOfDelivery = courierDeliveryType,
                ActualDistance = doDelivery.ActualDistance,
                TotalHandlingDuration = totalHandlingDuration,
                OrderClosedStatus = (BO.OrderEndStatus)doDelivery.OrderClosedStatus!,
                DeliveryEndTime = doDelivery.DeliveryEndTime
            };
        })
        .Where(bDelivery => !filterByType.HasValue || bDelivery.TypeOfOrder == filterByType.Value);

        return closedDeliveries;
    }

    /// <summary>
    /// sorts a collection of closed deliveries based on the specified field.
    /// </summary>
    /// <param name="deliveries"></param>
    /// <param name="sortBy"></param>
    /// <returns></returns>
    internal static IEnumerable<BO.ClosedDeliveryInList> SortClosedDeliveries(IEnumerable<BO.ClosedDeliveryInList> deliveries, BO.ClosedDeliveryFieldSort sortBy)
    {
        // sorts a collection of closed deliveries based on the specified field.
        return sortBy switch
        {
            BO.ClosedDeliveryFieldSort.OrderId => deliveries.OrderBy(d => d.OrderId),
            BO.ClosedDeliveryFieldSort.CompletionType => deliveries.OrderBy(d => d.OrderClosedStatus),
            BO.ClosedDeliveryFieldSort.TimeOfEnd => deliveries.OrderByDescending(d => d.DeliveryEndTime),
            BO.ClosedDeliveryFieldSort.TotalHandlingTime => deliveries.OrderBy(d => d.TotalHandlingDuration),
            _ => deliveries.OrderBy(d => d.OrderClosedStatus)
        };
    }

    /// <summary>
    /// gets all available open orders for a specific courier, optionally filtered by order type.
    /// When writing this function, we used AI to ensure that the logic and sorting order were correct.
    /// </summary>
    /// <param name="courierId"></param>
    /// <param name="filterByType"></param>
    /// <returns></returns>
    internal static IEnumerable<BO.OpenOrderInList> GetAvailableOpenOrders(int courierId, BO.OrderType? filterByType = null)
    {
        // gets all available open orders for a specific courier, optionally filtered by order type.
        DO.Courier doCourier = CourierManager.GetExistingCourier(courierId);

        // maximum distance restriction
        double maxDistance = doCourier.MaxDistance ?? double.MaxValue;

        // cordinates of the company (source)
        (double companyLat, double companyLon) = OrderManager.GetCompanyCoordinates();

        // retrieve open orders within the courier's maximum distance
        var availableOrders = s_dal.Order.ReadAll()
            .Where(o => o != null)
            .Where(o => filterByType == null || (BO.OrderType)o.TypeOfOrder == filterByType)
            .Where(o => OrderManager.CalculateOrderStatus(o.Id) == BO.OrderStatus.Open)

            // calculate air distance and filter by max distance
            .Select(o => new
            {
                Order = o,
                AirDistance = Tools.GetAirDistance(companyLat, companyLon, o.Latitude, o.Longitude)
            })
            .Where(item => item.AirDistance <= maxDistance)

            .Select(item =>
            {
                // map to BO.OpenOrderInList
                DO.Order doOrder = item.Order;
                double airDistance = item.AirDistance;

                // calculate timeliness status and remaining time
                BO.ScheduleStatus timeLinessStatus = OrderManager.CalculateScheduleStatus(doOrder.Id);
                DateTime maxDeliveryTime = OrderManager.CalculateMaxDeliveryTime(doOrder.Id);
                TimeSpan remainingTime = maxDeliveryTime - AdminManager.Now;

                // return the mapped BO.OpenOrderInList
                return new BO.OpenOrderInList
                {
                    Id = doOrder.Id,
                    OrderId = doOrder.Id,
                    TypeOfOrder = (BO.OrderType)doOrder.TypeOfOrder,
                    Address = doOrder.Address,
                    AirDistance = airDistance,
                    TimeLinessStatus = timeLinessStatus,
                    RemainingTime = remainingTime,
                    MaxDeliveryTime = maxDeliveryTime,
                    ActualDistance = null,
                    ActualTimeExtension = null
                };
            });

        return availableOrders;
    }

    /// <summary>
    /// sorts a collection of open orders based on the specified field.
    /// </summary>
    /// <param name="orders"></param>
    /// <param name="sortBy"></param>
    /// <returns></returns>
    internal static IEnumerable<BO.OpenOrderInList> SortOpenOrders(IEnumerable<BO.OpenOrderInList> orders, BO.OpenOrderFieldSort sortBy)
    {
        // sorts a collection of open orders based on the specified field.
        return sortBy switch
        {
            BO.OpenOrderFieldSort.Id => orders.OrderBy(o => o.OrderId),
            BO.OpenOrderFieldSort.TimeLinessStatus => orders.OrderByDescending(o => o.TimeLinessStatus),
            BO.OpenOrderFieldSort.ExpectedDeliveryTime => orders.OrderBy(o => o.ActualTimeExtension),
            BO.OpenOrderFieldSort.MaxDeliveryTime => orders.OrderBy(o => o.RemainingTime), // sorting by remaining time until max delivery time
            BO.OpenOrderFieldSort.AirDistance => orders.OrderBy(o => o.AirDistance),
            BO.OpenOrderFieldSort.ActualDistance => orders.OrderBy(o => o.ActualDistance),
            _ => orders.OrderByDescending(o => o.TimeLinessStatus)
        };
    }
}