using DalApi;

namespace Helpers;

internal static class DeliveryManager
{
    private static IDal s_dal = Factory.Get;

    /// <summary>
    /// Reads a single delivery record (internal).
    /// </summary>
    internal static DO.Delivery ReadDelivery(int deliveryId)
    {
        // Validate existence by calling the helper method.
        return GetExistingDelivery(deliveryId);
    }

    /// <summary>
    /// Reads all delivery records, optionally filtered by a predicate (internal).
    /// </summary>
    internal static IEnumerable<DO.Delivery> ReadAllDeliveries(Func<DO.Delivery, bool>? predicate = null)
    {
        return s_dal.Delivery.ReadAll(predicate);
    }

    /// <summary>
    /// Creates a new Delivery record for an Open order and an available courier.
    /// This includes performing the required routing calculation.
    /// </summary>
    /// <param name="orderId">The ID of the order being assigned.</param>
    /// <param name="courierId">The ID of the courier.</param>
    /// <param name="orderLat">Order's latitude.</param>
    /// <param name="orderLon">Order's longitude.</param>
    /// <param name="shippingType">The courier's shipping type.</param>
    internal static void CreateNewDeliveryForOrder(int orderId, int courierId, double orderLat, double orderLon, BO.DeliveryType shippingType)
    {
        // cordinates of the company (source)
        (double companyLat, double companyLon) = OrderManager.GetCompanyCoordinates();

        if (orderLat == 0 || orderLon == 0)
        {
            // default address value in Israel for routing to work
            orderLat = 32.07;
            orderLon = 34.77;
        }

        // calculate actual distance and estimated time
        (double actualDistance, TimeSpan estimatedTime)? routingResult;
        try
        {
            routingResult = Tools.GetActualDistanceAndEstimatedTimeSync(
                companyLat, companyLon, orderLat, orderLon, shippingType
            );
        }
        catch (Exception ex)
        {
            throw new BO.BlInvalidOperationException($"Routing failed. Please check internet and coordinates. Internal error: {ex.Message}");
        }

        if (!routingResult.HasValue)
        {
            throw new BO.BlInvalidOperationException("Routing service failed to calculate distance and time for the selected order/courier.");
        }

        // create new DO.Delivery record
        DateTime deliveryStartTime = AdminManager.Now;

        DO.Delivery newDelivery = new DO.Delivery(
            Id: default, // generated by DAL
            OrderId: orderId,
            CourierId: courierId,
            TypeOfOrder: OrderManager.GetExistingOrder(orderId).TypeOfOrder,
            DeliveryStartTime: deliveryStartTime,

            // saved values from routing calculation
            ActualDistance: routingResult.Value.actualDistance,

            OrderClosedStatus: null, // open
            DeliveryEndTime: null // open
        );

        // add to DAL
        s_dal.Delivery.Create(newDelivery);
    }

    /// <summary>
    /// Performs the final update for a delivery upon reported completion.
    /// </summary>
    /// <param name="deliveryId">The ID of the delivery record.</param>
    /// <param name="courierId">The courier ID reporting the completion (for internal validation).</param>
    /// <param name="completionStatus">The status upon completion (e.g., Delivered, Refused, etc.).</param>
    /// <exception cref="BO.BlDoesNotExistException">If Delivery record is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">If the delivery is already closed or courier ID does not match.</exception>
    internal static void CompleteDeliveryUpdate(int deliveryId, int courierId, BO.OrderEndStatus completionStatus, double endLat, double endLon)
    {
        // retrieve existing entities
        DO.Delivery doDelivery = GetExistingDelivery(deliveryId);
        DO.Order doOrder = OrderManager.GetExistingOrder(doDelivery.OrderId);
        DO.Courier doCourier = CourierManager.GetExistingCourier(courierId);

        // check courier assigned to delivery
        if (doDelivery.CourierId != courierId)
        {
            throw new BO.BlInvalidOperationException($"Courier {courierId} is not assigned to delivery {deliveryId}.");
        }

        // check courier ID matches
        if (doDelivery.DeliveryEndTime.HasValue)
        {
            throw new BO.BlInvalidOperationException($"Delivery {deliveryId} is already completed.");
        }

        // update delivery end time
        DateTime deliveryEndTime = AdminManager.Now;

        // retrieve company coordinates (source)
        (double startLat, double startLon) = OrderManager.GetCompanyCoordinates();

        // calculate actual distance from company to delivery end location
        (double actualDistance, TimeSpan estimatedTime)? routingResult = 
            Tools.GetActualDistanceAndEstimatedTimeSync(startLat, startLon, endLat, endLon,(BO.DeliveryType)doCourier.TypeOfDelivery);

        if (!routingResult.HasValue)
        {
            throw new BO.BlInvalidOperationException("Routing service failed to calculate actual distance at delivery completion.");
        }

        // update DO.Delivery record
        DO.Delivery updatedDelivery = doDelivery with
        {
            ActualDistance = routingResult.Value.actualDistance,
            OrderClosedStatus = (DO.OrderEndStatus)completionStatus,
            DeliveryEndTime = deliveryEndTime
        };
        s_dal.Delivery.Update(updatedDelivery);
    }

    /// <summary>
    /// Helper method to get an existing delivery or throw an exception if it does not exist.
    /// </summary>
    /// <param name="deliveryId"></param>
    /// <returns></returns>
    /// <exception cref="InvalidOperationException"></exception>
    private static DO.Delivery GetExistingDelivery(int deliveryId)
    {
        var delivery = s_dal.Delivery.Read(deliveryId);
        if (delivery == null)
        {
            throw new BO.BlDoesNotExistException($"Delivery with ID {deliveryId} does not exist.");
        } 
        return delivery;
    }

    /// <summary>
    /// Retrieves all closed deliveries for a specific courier, with optional filtering by order type.
    /// </summary>
    internal static IEnumerable<BO.ClosedDeliveryInList> GetClosedDeliveriesForCourier(
        int courierId,
        BO.OrderType? filterByType = null)
    {
        // retrieves all closed deliveries for a specific courier, with optional filtering by order type.
        var deliveries = s_dal.Delivery.ReadAll(d =>
            d.CourierId == courierId &&
            d.DeliveryEndTime.HasValue);

        // map DO.Delivery to BO.ClosedDeliveryInList 
        var closedDeliveries = deliveries.Select(doDelivery =>
        {
            // retrieve associated order
            DO.Order doOrder = OrderManager.GetExistingOrder(doDelivery.OrderId);

            // calculate TotalHandlingDuration
            TimeSpan totalHandlingDuration = doDelivery.DeliveryEndTime!.Value - doDelivery.DeliveryStartTime;

            return new BO.ClosedDeliveryInList
            {
                Id = doDelivery.Id,
                OrderId = doDelivery.OrderId,
                TypeOfOrder = (BO.OrderType)doOrder.TypeOfOrder,
                Address = doOrder.Address,
                TypeOfDelivery = (BO.DeliveryType)s_dal.Courier.Read(courierId)!.TypeOfDelivery,
                ActualDistance = doDelivery.ActualDistance,
                TotalHandlingDuration = totalHandlingDuration,
                OrderClosedStatus = (BO.OrderEndStatus)doDelivery.OrderClosedStatus!,
                DeliveryEndTime = doDelivery.DeliveryEndTime
            };
        })
        .Where(bDelivery => !filterByType.HasValue || bDelivery.TypeOfOrder == filterByType.Value); // filter by type if needed

        return closedDeliveries;
    }

    /// <summary>
    /// Sorts a collection of closed deliveries based on the specified field.
    /// </summary>
    internal static IEnumerable<BO.ClosedDeliveryInList> SortClosedDeliveries(IEnumerable<BO.ClosedDeliveryInList> deliveries, BO.ClosedDeliveryFieldSort sortBy)
    {
        return sortBy switch
        {
            BO.ClosedDeliveryFieldSort.OrderId => deliveries.OrderBy(d => d.OrderId),
            BO.ClosedDeliveryFieldSort.CompletionType => deliveries.OrderBy(d => d.OrderClosedStatus),
            BO.ClosedDeliveryFieldSort.TimeOfEnd => deliveries.OrderByDescending(d => d.DeliveryEndTime),
            BO.ClosedDeliveryFieldSort.TotalHandlingTime => deliveries.OrderBy(d => d.TotalHandlingDuration),
            _ => deliveries.OrderBy(d => d.OrderClosedStatus)
        };
    }

    /// <summary>
    /// Retrieves all open orders that are within the specified courier's maximum distance limit,
    /// with optional filtering by order type.
    /// </summary>
    internal static IEnumerable<BO.OpenOrderInList> GetAvailableOpenOrders(int courierId, BO.OrderType? filterByType = null)
    {
        // retrieving courier's max distance
        DO.Courier doCourier = CourierManager.GetExistingCourier(courierId);
        double maxDistance = doCourier.MaxDistance ?? double.MaxValue; // use a very large number if no limit

        // retrieving company coordinates
        (double companyLat, double companyLon) = OrderManager.GetCompanyCoordinates();

        // retrieving all open orders
        var allOpenOrders = s_dal.Order.ReadAll().Select(o => o.Id) // getting all order IDs
            .Where(id => OrderManager.CalculateOrderStatus(id) == BO.OrderStatus.Open); // filtering open orders

        // mapping and filtering
        var availableOpenOrders = allOpenOrders.Select(orderId =>
        {
            DO.Order doOrder = OrderManager.GetExistingOrder(orderId);

            // calculate air distance
            double airDistance = Tools.GetAirDistance(companyLat, companyLon, doOrder.Latitude, doOrder.Longitude);

            // calculate time-liness status and remaining time
            BO.ScheduleStatus timeLinessStatus = OrderManager.CalculateScheduleStatus(orderId);
            DateTime maxDeliveryTime = OrderManager.CalculateMaxDeliveryTime(orderId);
            TimeSpan remainingTime = maxDeliveryTime - AdminManager.Now;

            // calculate actual distance and estimated time using routing service
            (double actualDistance, TimeSpan estimatedTime)? routingResult = Tools
                .GetActualDistanceAndEstimatedTimeSync(companyLat, companyLon, doOrder.Latitude, doOrder.Longitude, (BO.DeliveryType)doCourier.TypeOfDelivery);

            // mapping to BO.OpenOrderInList
            double? finalActualDistance = routingResult?.actualDistance;
            TimeSpan? finalEstimatedDuration = routingResult?.estimatedTime;

            return new BO.OpenOrderInList
            {
                // basic order data
                OrderId = doOrder.Id,
                TypeOfOrder = (BO.OrderType)doOrder.TypeOfOrder,
                Address = doOrder.Address,
                AirDistance = airDistance,

                // logistic data
                TimeLinessStatus = timeLinessStatus,
                RemainingTime = remainingTime,
                MaxDeliveryTime = maxDeliveryTime,

                // data from routing calculation
                ActualDistance = finalActualDistance,
                ActualTimeExtension = finalEstimatedDuration,
            };
        })
        // filter by max distance
        .Where(bOrder => bOrder.AirDistance <= maxDistance)
        // filter by type if needed
        .Where(bOrder => !filterByType.HasValue || bOrder.TypeOfOrder == filterByType.Value);

        return availableOpenOrders;
    }

    /// <summary>
    /// Sorts a collection of open orders based on the specified field.
    /// </summary>
    internal static IEnumerable<BO.OpenOrderInList> SortOpenOrders(IEnumerable<BO.OpenOrderInList> orders, BO.OpenOrderFieldSort sortBy)
    {
        return sortBy switch
        {
            BO.OpenOrderFieldSort.Id => orders.OrderBy(o => o.OrderId),
            BO.OpenOrderFieldSort.TimeLinessStatus => orders.OrderBy(o => o.TimeLinessStatus),
            BO.OpenOrderFieldSort.ExpectedDeliveryTime => orders.OrderBy(o => o.ActualTimeExtension),
            BO.OpenOrderFieldSort.MaxDeliveryTime => orders.OrderBy(o => o.RemainingTime), // sorting by remaining time until max delivery time
            BO.OpenOrderFieldSort.AirDistance => orders.OrderBy(o => o.AirDistance),
            BO.OpenOrderFieldSort.ActualDistance => orders.OrderBy(o => o.ActualDistance),
            _ => orders.OrderBy(o => o.TimeLinessStatus)
        };
    }
}

